"""modify snapshot model

Revision ID: 33164f731ca9
Revises: 0678e0163d88
Create Date: 2024-12-28 12:31:08.766484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33164f731ca9'
down_revision: Union[str, None] = '0678e0163d88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('snapshots_snapshot_id_key', 'snapshots', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('snapshots_snapshot_id_key', 'snapshots', ['snapshot_id'])
    # ### end Alembic commands ###
