"""profile completetion check

Revision ID: 47cecc079359
Revises: 10a0c77bd5d6
Create Date: 2024-12-25 18:51:41.412009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47cecc079359'
down_revision: Union[str, None] = '10a0c77bd5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('is_profile_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'is_profile_complete')
    # ### end Alembic commands ###
