"""Add user_recommendations table

Revision ID: d27a8089ff3b
Revises: d4af54f9578b
Create Date: 2024-12-24 00:42:24.871948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd27a8089ff3b'
down_revision: Union[str, None] = 'd4af54f9578b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_recommendations_id'), 'user_recommendations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_recommendations_id'), table_name='user_recommendations')
    op.drop_table('user_recommendations')
    # ### end Alembic commands ###
