"""Initial migration

Revision ID: d4af54f9578b
Revises: 
Create Date: 2024-12-23 19:27:34.847813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4af54f9578b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('current_title', sa.String(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('current_industry', sa.String(), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('career_goals', sa.Text(), nullable=True),
    sa.Column('preferred_job_titles', sa.Text(), nullable=True),
    sa.Column('preferred_industries', sa.Text(), nullable=True),
    sa.Column('salary_expectations', sa.Float(), nullable=True),
    sa.Column('relocation_willingness', sa.Boolean(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('portfolio', sa.String(), nullable=True),
    sa.Column('resume_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_email'), 'user_profiles', ['email'], unique=True)
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_email'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
