"""Add user_recommendations table

Revision ID: dff6ac155ed5
Revises: d27a8089ff3b
Create Date: 2024-12-24 00:43:09.039460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dff6ac155ed5'
down_revision: Union[str, None] = 'd27a8089ff3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
